### ISSUE TITLE
ReferenceError: ace is not defined

### ISSUE THREAD

**Issue by alissa-huskey** [Aerilius/sketchup-console-plus#41] opened 2023-05-02 17:37 UTC
### Editor

* No Syntax highlighting
* No auto-indenting or other formatting nicities
* Autocomplete and tooltips are inconsistent--they seem not to appear on any attributes or methods after the first value. (ie, both will appear for `Sketchup` but not `Sketchup.active_model`)
* No entity inspection

### Other

* When you click the `?`, the Documentation window is blank

## Error Message

After opening the Ruby Console+ window, the following error message appears:

```
(JavaScript) ReferenceError: ace is not defined
    at ~/Library/Application%20Support/SketchUp%202022/SketchUp/Plugins/ae_console/external/ace/mode-ruby_sketchup.js:1:1
(JavaScript) Error: Script error for "ace/mode/ruby_sketchup"
http://requirejs.org/docs/errors.html#scripterror
http://requirejs.org/docs/errors.html#scripterror
    at makeError (~/Library/Application%20Support/SketchUp%202022/SketchUp/Plugins/ae_console/external/requirejs/require.js:5:1067)
    at HTMLScriptElement.onScriptError (~/Library/Application%20Support/SketchUp%202022/SketchUp/Plugins/ae_console/external/requirejs/require.js:5:13218)
```

## Environment Information

* **Machine**: MacBook Pro 2021 (arm64, Apple M1 Max)
* **OS**: macOS Ventura 13.2.1
* **SketchUp**: SketchUp Pro 2022 Version 22.0.353, SketchUp Pro 2023 Version 23.0.418
* **Ruby Console+**: 3.14, 3.17
* **`RUBY_VERSION`**: 2.7.7

**Comment by alissa-huskey** [comment] 2023-05-16 19:15
Just to add a little more detail, it is intermittent though happens more often than not. I'm pretty sure it's a race condition of some sort having to do with the load order of the `ace` library when loading the file `mode-ruby_sketchup.js`.

**Comment by Aerilius** [comment] 2024-12-04 22:59
Thanks for your fixes! This was caused by an update of ace, where I had not adjusted the custom file. I have merged you pull request.

**Closed as completed by Aerilius** 2024-12-04 22:59 UTC
